@domain = {{$dotenv API_DOMAIN}}

##################### Test API's favorite.py #####################
#Test Like recipe
POST {{domain}}/api/menu/favorite
Content-Type: application/json

{
    "uid": 6,
    "menuid": 2
}

###
#Test Deleting favorite's recipe
@Dfavoriteid = 1
DELETE  http://127.0.0.1:5000/api/menu/delete/{{Dfavoriteid}}