###
DELETE http://127.0.0.1:5000/api/menu/1/1

###
POST http://127.0.0.1:5000/api/menu/addss
Content-Type: application/json

  {
    "createruid": 1,
    "menuName": "Corndog",
    "estimateTime": "00:17:00",
    "categoryid": 1 ,
    "ingredients" : [
    {"ingredientname": "Ingredient A", "quantity": 100},
    {"ingredientname": "Ingredient B", "quantity": 12},
    {"ingredientname": "Ingredient C", "quantity": 35},
    {"ingredientname": "Ingredient D", "quantity": 62},
    {"ingredientname": "Ingredient E", "quantity": 1},
    {"ingredientname": "Ingredient F", "quantity": 4},
    {"ingredientname": "Ingredient G", "quantity": 9},
    {"ingredientname": "Ingredient H", "quantity": 34},
    {"ingredientname": "Ingredient I", "quantity": 126},
    {"ingredientname": "Ingredient J", "quantity": 621},
    {"ingredientname": "Ingredient K", "quantity": 216}
  ] , 
  "kitchentools": [
    "Chef's Knife",
    "Cutting Board",
    "Mixing Bowls",
    "Whisk",
    "Measuring Cups",
    "Measuring Spoons",
    "Spatula",
    "Frying Pan",
    "Pot",
    "Peeler",
    "Grater",
    "Can Opener"
  ] ,
  "stepsdetail": [
    "Cut ingredient",
    "Cut meat",
    "Boiling water"
  ]
  }


###

PUT http://127.0.0.1:5000/api/menu/update/38 
Content-Type: application/json

  {
    "createruid": 1,
    "menuName": "Corndog",
    "estimateTime": "00:17:00",
    "categoryid": 1 ,
    "ingredients" : [
    {"ingredientname": "Ingredient A", "quantity": 120},
    {"ingredientname": "Ingredient B", "quantity": 12},
    {"ingredientname": "Ingredient C", "quantity": 35},
    {"ingredientname": "Ingredient D", "quantity": 62},
    {"ingredientname": "Ingredient E", "quantity": 1},
    {"ingredientname": "Ingredient F", "quantity": 4},
    {"ingredientname": "Ingredient G", "quantity": 9},
    {"ingredientname": "Ingredient H", "quantity": 34},
    {"ingredientname": "Ingredient I", "quantity": 126},
    {"ingredientname": "Ingredient J", "quantity": 621},
    {"ingredientname": "Ingredient K", "quantity": 216}
  ] , 
  "kitchentools": [
    "Chef's K",
    "Cutting B",
    "Mixing B",
    "W",
    "Measuring ",
    "Measuring Spoons",
    "Spatula",
    "Frying Pan",
    "Pot",
    "Peeler",
    "Grater",
    "Can Opener"
  ] ,
  "stepsdetail": [
    "Cut you",
    "Boiling water"
  ]
  }
