POST http://127.0.0.1:5000/api/menu/public
Content-Type: application/json

{
    "menuid": 6,
    "publicStatus": 1
}

###

PUT http://127.0.0.1:5000/api/menu/public/update
Content-Type: application/json

{
    "menuid": 6,
    "publicStatus": 0
}